title: Michael Rich
logo: "me.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <a href="/pdf/Michael_Rich_Resume.pdf" class="btn btn--info">Resume</a>  
  <br>
  <a href="https://www.linkedin.com/in/michaelrich01" class="btn btn--info">LinkedIn</a>  
  <br>
  <a href="https://github.com/mikebrich">GitHub</a>  
  
theme: jekyll-theme-minimal
